site:
  name: DevFest Florida
  site: 'https://devfestflorida.com/'
  base: '/'
  trailingSlash: false

# Default SEO metadata
metadata:
  title:
    default: DevFest Florida
    template: '%s — DevFest Florida'
  description: "\U0001F334 Devfest Central Florida Hackathon is Coming Soon!"
  robots:
    index: true
    follow: true
  openGraph:
    site_name: DevFest Florida
    images:
      - url: '~/assets/images/devfest-hackathon-2025-date.png'
        width: 1920
        height: 1080
    type: website
  twitter:
    handle: '@devfestfl'
    site: '@devfestfl'
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: true
    postsPerPage: 10

    post:
      isEnabled: true
      permalink: '/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog' # Blog main path, you can change this to "articles" (/articles)
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: null # or "G-XXXXXXXXXX"

ui:
  theme: 'system' # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
